### ISSUE TITLE
Support hyphen '-' in token names

### ISSUE THREAD

**Issue by pholden77** [sqlcollaborative/dbops#111]
The Regex used to replace token values only supports [a-zA-Z0-9\.].  

I'm migrating some existing scripts to dbops and we have token names contaning a -

e.g. #{app-DatabaseName}

I think it's just line 27 in *internal/functions/Resolve-VariableToken.ps1* that needs to change.

**Comment by nvarscar** [comment]
I agree, hyphen should be supported in the token name. And it does seem like an easy fix, I'll PR a fix shortly.

**Comment by nvarscar** [comment]
Added in v0.6.3

**Comment by pholden77** [comment]
Working perfectly for me, thanks for the quick response.
