### ISSUE TITLE
[New feature] More journaling metadata

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbops#120]
Add more columns to the SchemaVersions table. Thinking of ones along the lines of what [flyway has](https://flywaydb.org/documentation/commandline/info) like user, status, file hash, etc.

**Comment by nvarscar** [comment]
This is definitely something I contemplated in the past, and this would make a great addition to the module. I'll see what I can do. Thanks for the feedback!

**Comment by nvarscar** [comment]
Just wanted to give an update on this one, it took much more thought that I originally envisioned, but I'm finally happy with how it's coming together. This should be available as soon as 0.7.0 is released.

**Comment by nvarscar** [comment]
Implemented in #126

**Comment by LowlyDBA** [comment]
Awesome! Great enhancement to add value to the project.

Thank you!
