### ISSUE TITLE
Type error in deploy.ps1 - [DBOpsConfig] class cannot be referenced

### ISSUE THREAD

**Issue by piroinno** [sqlcollaborative/dbops#78]
Importing the dbops module in the deploy.ps1 file does not load the DBOpsConfig class referenced on line 46.

Issue should be solved by sourcing . "$PSScriptRoot\Modules\dbops\internal\classes\DBOps.class.ps1"

**Comment by nvarscar** [comment]
Thanks for bringing this up, this is clearly a bug. The class is supposed to be for internal use only and it simply shouldn't even be mentioned in the deploy file.

**Comment by nvarscar** [comment]
Resolved in 0.5.5.
